### ISSUE TITLE
Crash when placing chickens into breeder in specific blocks in the world

### ISSUE THREAD

**Issue by GorgleRanking** [TarantelTM/roost_ultimate#10]
Whenever i place a type of chicken (tried with bone and coal) into a breeder my game crashes with this error. I have no idea why this randomly started happening, as i had used breeders without issue for the first 35 days of the world. The issue seems to be relegated to a specific few blocks in the world. It is not limited to the chunk, as i can place working breeders in MOST of the chunk, there are simply a few blocks that immediately crash the game and make me remove the mod to get back in the world as it crashes immediately. I can still use breeders perfectly fine in the other 99% of the world, but having to remove the mod to fix it thus losing all my progress is a bit frustrating.

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2024-07-11 03:43:59
Description: Ticking block entity

java.lang.IllegalStateException: Unable to get Y-rotated facing of down
	at net.minecraft.class_2350.method_10170(class_2350.java:182)
	at net.tarantel.chickenroost.block.entity.breeder_entity.method_5493(breeder_entity.java:216)
	at alexiil.mc.lib.attributes.item.compat.FixedSidedInventoryVanillaWrapper.canExtract(FixedSidedInventoryVanillaWrapper.java:35)
	at alexiil.mc.lib.attributes.item.compat.FixedInventoryVanillaWrapper.setInvStack(FixedInventoryVanillaWrapper.java:34)
	at alexiil.mc.lib.attributes.item.FixedItemInv.extractStack(FixedItemInv.java:164)
	at alexiil.mc.lib.attributes.item.impl.GroupedItemInvFixedWrapper.attemptExtraction(GroupedItemInvFixedWrapper.java:60)
	at alexiil.mc.lib.attributes.item.impl.CombinedItemExtractable.attemptExtraction(CombinedItemExtractable.java:35)
	at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:110)
	at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:91)
	at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:82)
	at alexiil.mc.lib.attributes.item.mixin.HopperHooks.tryExtract(HopperHooks.java:95)
	at net.minecraft.class_2614.handler$cdk000$libblockattributes_items$onExtract(class_2614.java:1544)
	at net.minecraft.class_2614.method_11241(class_2614.java)
	at net.minecraft.class_2614.method_31691(class_2614.java:102)
	at net.minecraft.class_2614.method_11243(class_2614.java:118)
	at net.minecraft.class_2614.method_31692(class_2614.java:102)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2350.method_10170(class_2350.java:182)
	at net.tarantel.chickenroost.block.entity.breeder_entity.method_5493(breeder_entity.java:216)
	at alexiil.mc.lib.attributes.item.compat.FixedSidedInventoryVanillaWrapper.canExtract(FixedSidedInventoryVanillaWrapper.java:35)
	at alexiil.mc.lib.attributes.item.compat.FixedInventoryVanillaWrapper.setInvStack(FixedInventoryVanillaWrapper.java:34)
	at alexiil.mc.lib.attributes.item.FixedItemInv.extractStack(FixedItemInv.java:164)
	at alexiil.mc.lib.attributes.item.impl.GroupedItemInvFixedWrapper.attemptExtraction(GroupedItemInvFixedWrapper.java:60)
	at alexiil.mc.lib.attributes.item.impl.CombinedItemExtractable.attemptExtraction(CombinedItemExtractable.java:35)
	at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:110)
	at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:91)
	at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:82)
	at alexiil.mc.lib.attributes.item.mixin.HopperHooks.tryExtract(HopperHooks.java:95)
	at net.minecraft.class_2614.handler$cdk000$libblockattributes_items$onExtract(class_2614.java:1544)
	at net.minecraft.class_2614.method_11241(class_2614.java)
	at net.minecraft.class_2614.method_31691(class_2614.java:102)
	at net.minecraft.class_2614.method_11243(class_2614.java:118)
	at net.minecraft.class_2614.method_31692(class_2614.java:102)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.class_2614
	Block: Block{minecraft:hopper}[enabled=true,facing=down]
	Block location: World: (796,-53,71), Section: (at 12,11,7 in 49,-4,4; chunk contains blocks 784,-64,64 to 799,319,79), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,-64,0 to 1023,319,511)
	Block: Block{minecraft:hopper}[enabled=true,facing=down]
	Block location: World: (796,-53,71), Section: (at 12,11,7 in 49,-4,4; chunk contains blocks 784,-64,64 to 799,319,79), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,-64,0 to 1023,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Shyest'/121, l='ServerLevel[1.20.1 modded]', x=799.25, y=-54.00, z=71.82]]
	Chunk stats: 5018
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,73,16), Section: (at 0,9,0 in -1,4,1; chunk contains blocks -16,-64,16 to -1,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1155588 game time, 1316131 day time
	Level name: 1.20.1 modded
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 25352 (now: false), thunder time: 150624 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1274267880 bytes (1215 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.61
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0x9a68
	Graphics card #0 versionInfo: DriverVersion=31.0.101.5186
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a2
	Graphics card #1 versionInfo: DriverVersion=32.0.15.5612
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18964.30
	Virtual memory used (MB): 16956.65
	Swap memory total (MB): 11045.51
	Swap memory used (MB): 1899.45
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ae2: Applied Energistics 2 15.2.0
			team_reborn_energy: Energy 3.0.0
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		architectury: Architectury 9.1.10
		azurelib: AzureLib 1.0.19
			com_eliotlash_mclib_mclib: mclib 20
		badpackets: Bad Packets 0.4.1
		bettercombat: Better Combat 1.7.2+1.20.1
		bookshelf: Bookshelf 20.0.1
		chicken_roost: Roost Ultimate 0.9.9-1.20.1
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		conjuring: Conjuring 1.0.28+1.20
			lavender: Lavender 0.1.0-pre.6+1.20
				lavender-md: lavender-md 0.1.0-pre.3+1.20
				lavender-md-owo-ui: lavender-md-owo-ui 0.1.0-pre.3+1.20
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		cristellib: Cristel Lib 1.1.1
		croptopia: Croptopia 2.3.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		ctov: ChoiceTheorem's Overhauled Village 3.3.2
		darkutils: DarkUtilities 17.0.1
		doapi: Lets Do Api 1.2.4
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		dungeons_arise: When Dungeons Arise 2.1.56.1
		enchantinginfuser: Enchanting Infuser 8.0.1
		enchdesc: EnchantmentDescriptions 17.0.1
		explorations: Explorations 1.20.1-1.5.2
		explorify: Explorify v1.3.0-mc1.20u1.20.1
		extractinator: Extractinator 2.2.0
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fallingtree: FallingTree 4.2.0
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		framework: Framework 0.6.16
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		friendsandfoes: Friends&Foes 1.9.3
		fwaystones: Fabric Waystones 3.1.2+mc1.20
		geckolib: Geckolib 4.2.1
		geode_plus: Geode+ 1.2.0
			paragon: Paragon 3.0.2
				com_moandjiezana_toml_toml4j: toml4j 0.7.2
		geodes: More Geodes 1.8.2
		gravestones: Gravestones v1.15
		handcrafted: Handcrafted 2.3.2
		hwg: Happiness is a Warm Gun 1.4.14
		immersive_aircraft: Immersive Aircraft 0.5.1+1.20.1
		ironchests: Iron Chests: Restocked 5.0.2
		itemcollectors: Item Collectors 1.1.10
		jamlib: JamLib 0.6.0+1.20
		java: OpenJDK 64-Bit Server VM 17
		mca: Minecraft Comes Alive 7.5.3+1.20.1
		mcda: MC Dungeons Armors 5.0.0
		mcdar: MC Dungeons Artifacts 3.0.0
		mcdw: MC Dungeons Weapons 8.0.3
		mcpitanlib: MCPitanLib 2.2.4-1.20.1-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		minecraft: Minecraft 1.20.1
		moblassos: Mob Lassos 8.0.0
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			extensibleenums: Extensible Enums 7.0.1
		mr_camps_castles_carriages: Camps. Castles. Carriages. 2.3.3
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v2.1.4
		mythicmetals: Mythic Metals 0.19.9+1.20.1
			additionalentityattributes: Additional Entity Attributes 1.7.3+1.20.0
			common-protection-api: Common Protection API 1.0.0
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		patchouli: Patchouli 1.20.1-81-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.7+1.14.4-1.20.1
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		philipsruins: Philip`s Ruins 1.20.1
		piercingpaxels: piercingpaxels 1.0.11
		pipeplus: PipePlus 1.20.1-1.1.4-fix.1
			libblockattributes: LibBlockAttributes 0.14.0-pre.1
				libblockattributes_core: LibBlockAttributes (Core) 0.14.0-pre.1
				libblockattributes_fluids: LibBlockAttributes (Fluids) 0.14.0-pre.1
				libblockattributes_items: LibBlockAttributes (Items) 0.14.0-pre.1
			libmultipart: LibMultiPart 0.11.0-pre.2
			libnetworkstack: Lib Network Stack 0.10.0-pre.2
		player-animator: Player Animator 1.0.2-rc1+1.20
		puzzleslib: Puzzles Lib 8.0.7
		quarrymod: Industrial Quarry Mod 1.2.0
		resourcefulconfig: Resourcefulconfig 2.0.0
		resourcefullib: Resourceful Lib 2.1.4
			com_teamresourceful_yabn: yabn 1.0.3
		roughlyenoughitems: Roughly Enough Items 12.0.634
			error_notifier: Error Notifier 1.0.9
		seasons: Fabric Seasons 2.2.1+1.20
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.11.0-pre.2
			libmultipart_compat: LibMultiPart (Mod Compatibility) 0.11.0-pre.2
			simple_pipes: SimplePipeTest 0.11.0-pre.2
		simply_houses: Simply Houses 1.1.4-1.20.1
		simplyswords: Simply Swords 1.48.1-1.21
		skyvillages: Sky Villages 1.0.2.1-1.20.1
		smallships: Small Ships 2.0.0-b1.3.1
		smartbrainlib: SmartBrainLib 1.11.1
		sodium: Sodium 0.5.11+mc1.20.1
		structory: Structory 1.3.2
		structory_towers: Structory: Towers 1.0.3
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.7
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.11
		t_and_t: Towns and Towers 1.10.2
		techreborn: Tech Reborn 5.8.7
			reborncore: Reborn Core 5.8.7
		terrestria: Terrestria 6.0.8
			biolith: Biolith 1.0.0-alpha.8
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.1
			terraform-config-api-v1: Terraform Config API (v1) 7.0.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 7.0.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.1
			terraform-tree-api-v1: Terraform Tree API (v1) 7.0.1
			terrestria-client: Terrestria: Client 6.0.8
			terrestria-common: Terrestria: Common 6.0.8
			terrestria-worldgen: Terrestria: World Generation 6.0.8
		things: Things 0.3.1+1.20
		travelersbackpack: Traveler's Backpack fabric-1.20.1-9.1.15
		trinkets: Trinkets 3.7.0
		twigs: Twigs 3.1.0
		ultris_mr: Ultris: Boss Expansion 5.6.9b
		wthit: wthit 8.1.1
		xaerominimap: Xaero's Minimap 23.5.0
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['Shyest'/121, l='ServerLevel[1.20.1 modded]', x=799.25, y=-54.00, z=71.82]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.11-1.20.1

**Comment by TarantelTM** [comment]
Hello,

Atm i have no eta on new versions of my Mod for Fabric.
I know it got still some bugs but this looks more like a problem with Lib Multipart.
Would prefer to ask in lib multipart github page for help and maybe he knows how to deal with it or refback to me.
But i cant see any problems with my mod atm in your crash log.

**Comment by GorgleRanking** [comment]
Thanks for responding so soon, will definitely do as you suggested.
