### ISSUE TITLE
Chickens inside roosts go over the max level and stop producing resources

### ISSUE THREAD

**Issue by Blitzsy** [TarantelTM/roost_ultimate#2]
Modloader: Forge
Minecraft Version: 1.20.1
Mod Version: 2.1.2
Source ?: Curseforge
Used in Modpack ?: ATM9 (9-0.2.24)
Own added Mods: N/A

If its something like a Crash or other visible Error inside MC, please create Gists of Crash Log and Latest Logs.
Latest.log minecraftinstance/logs/
Debug.log minecraftinstance/logs/
Crashreports minecraftinstance/crash-reports/ (server, client and fml please).
Link to Github Gist: https://gist.github.com/
Add the link here.

Description of your Problem: Chickens inside roosts can go over the max level cap (61/60) and no longer produce resources.

**Comment by TarantelTM** [comment]
thanks for the info, will check it this weekend.

**Comment by TarantelTM** [comment]
Fixed in the latest Version 1.20.1-2.1.3
