### ISSUE TITLE
Bone chicken

### ISSUE THREAD

**Issue by craken83** [TarantelTM/roost_ultimate#3]
Modloader: Forge 
Minecraft Version: 1.20.1
Mod Version: 2.1.3
Source : Curseforge
Used in Modpack : private modpack
Own added Mods: 
![image](https://github.com/TarantelTM/Roost_Ultimate/assets/35100594/3053a3a0-97d3-4c3f-8aa4-035c90fa1ff1)
![image](https://github.com/TarantelTM/Roost_Ultimate/assets/35100594/33d55981-a0fa-47b0-8f45-b6d160fcf9af)
![image](https://github.com/TarantelTM/Roost_Ultimate/assets/35100594/a49f0b11-9f28-47ca-b653-eede2a5ff061)

If its something like a Crash or other visible Error inside MC, please create Gists of Crash Log and Latest Logs.
Latest.log minecraftinstance/logs/
Debug.log minecraftinstance/logs/
Crashreports minecraftinstance/crash-reports/ (server, client and fml please).
Link to Github Gist: https://gist.github.com/
Add the link here.

Description of your Problem: The BoneChicken don't spawn or aren't obtainable in survival.

**Comment by craken83** [comment]
@TarantelTM can you help me please?

**Comment by TarantelTM** [comment]
should be fixed in the last version 2.1.4
